name: Dependency Review

on:
  pull_request:
    branches: [main, develop, "release/**", "support/**"]

permissions: {}

jobs:
  dependency-review:
    name: Dependency review
    permissions:
      contents: read
    uses: t33n-software/repository-governance/.github/workflows/reusable-dependency-review.yml@842c23028f0635a6478b727248033731693139a4
