name: Dependency Review

on:
  pull_request:
    branches: [main, develop, "release/**", "support/**"]

permissions: {}

jobs:
  dependency-review:
    name: Dependency review
    permissions:
      contents: read
    uses: t33n-software/repository-governance/.github/workflows/reusable-dependency-review.yml@c4d870b7e24d8959c13b46b935983877a349b2b4
