name: Dependency Review

on:
  pull_request:
    branches: [main, develop, "release/**", "support/**"]

permissions: {}

jobs:
  dependency-review:
    name: Dependency review
    permissions:
      contents: read
    uses: t33n-software/repository-governance/.github/workflows/reusable-dependency-review.yml@97dee624ecbff827619d781233aceb0b359a7120
